# Generated by Django 3.1.4 on 2021-01-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210101_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
    ]
