# Generated by Django 3.1.4 on 2021-01-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210102_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollment',
            new_name='enrolment',
        ),
    ]
