# Generated by Django 3.1.4 on 2021-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210102_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirm_passwd',
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=70, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=70, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passwd',
            field=models.CharField(max_length=70, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=70, verbose_name='Username'),
        ),
    ]
