# Generated by Django 3.1.4 on 2021-01-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210102_1456'),
        ('students', '0006_auto_20210102_1556'),
    ]

    operations = [
    ]
