# Generated by Django 3.1.4 on 2021-01-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_merge_20210102_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CE', 'Computer Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics and Comm. Engineering'), ('BME', 'Bio-Medical Engineering'), ('MC', 'Mechantronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Marine Engineering'), ('AE', 'Automobile Engineering'), ('PE', 'Petrochemical Engineering')], max_length=70, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], max_length=5, verbose_name='Semester'),
        ),
    ]
