# Generated by Django 3.1.4 on 2021-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_ispending'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_id',
            field=models.CharField(default='', max_length=20, verbose_name='Account Id'),
        ),
    ]
