# Generated by Django 3.1.4 on 2021-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('Student', 'Student')], default='Student', max_length=30, verbose_name='Category'),
        ),
    ]
