# Generated by Django 3.1.4 on 2021-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('Student', 'Student')], default='Student', max_length=70, verbose_name='Category'),
        ),
    ]
