# Generated by Django 3.1.4 on 2021-01-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff1',
            name='sem',
        ),
    ]
