# Generated by Django 3.1.4 on 2021-01-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff1_sem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff1',
            new_name='Staff',
        ),
    ]
