# Generated by Django 3.1.4 on 2021-01-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210101_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='fullname',
        ),
        migrations.AddField(
            model_name='staff',
            name='firstName',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='staff',
            name='lastName',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='staff',
            name='middleName',
            field=models.CharField(default='', max_length=70),
        ),
    ]
