# Generated by Django 3.1.4 on 2021-01-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='college',
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.CharField(choices=[('CE', 'Computer Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics and Comm. Engineering'), ('BME', 'Bio-Medical Engineering'), ('MC', 'Mechantronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Marine Engineering'), ('AE', 'Automobile Engineering'), ('PE', 'Petrochemical Engineering')], max_length=70),
        ),
    ]
