# Generated by Django 3.1.4 on 2021-01-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210101_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
