# Generated by Django 3.1.4 on 2021-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('PROF', 'Professor'), ('APROF', 'Assistant Professor'), ('LI', 'Lab Instructor'), ('LA', 'Lab Assistant')], max_length=20, verbose_name='Designation'),
        ),
    ]
