# Generated by Django 3.1.4 on 2021-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staff_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Information Technology', 'Information Technology'), ('Electronics and Comm. Engineering', 'Electronics and Comm. Engineering'), ('Bio-Medical Engineering', 'Bio-Medical Engineering'), ('Mechantronics Engineering', 'Mechantronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Marine Engineering', 'Marine Engineering'), ('Automobile Engineering', 'Automobile Engineering'), ('Petrochemical Engineering', 'Petrochemical Engineering')], max_length=70, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('Head of Department', 'Head of Department'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lab Instructor', 'Lab Instructor'), ('Lab Assistant', 'Lab Assistant')], max_length=20, verbose_name='Designation'),
        ),
    ]
