# Generated by Django 3.1.4 on 2021-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20210103_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='account_id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Account Id'),
        ),
    ]
