# Generated by Django 3.1.4 on 2021-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20210103_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Admin', 'Admin'), ('Head of Department', 'Head of Department')], default='Faculty', max_length=70, verbose_name='Category'),
        ),
    ]
