# Generated by Django 3.1.4 on 2021-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_staff_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.CharField(max_length=70, verbose_name='Branch'),
        ),
    ]
