# Generated by Django 3.1.4 on 2021-01-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_auto_20210124_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.CharField(choices=[], max_length=70, verbose_name='Branch'),
        ),
    ]
