# Generated by Django 3.1.4 on 2021-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=70, verbose_name='First Name')),
                ('lastName', models.CharField(default='', max_length=70, verbose_name='Last Name')),
                ('username', models.CharField(max_length=70, verbose_name='Username')),
                ('passwd', models.CharField(max_length=70, verbose_name='Password')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('category', models.CharField(max_length=70, verbose_name='User Category')),
                ('isAdmin', models.BooleanField(default=False, max_length=10)),
            ],
        ),
    ]
