# Generated by Django 3.1.4 on 2021-01-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_appuser_ispending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
