# Generated by Django 3.1.4 on 2021-01-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210103_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=70, primary_key=True, serialize=False, unique=True, verbose_name='Username'),
        ),
    ]
