# Generated by Django 3.1.4 on 2021-01-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210107_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
