# Generated by Django 3.1.4 on 2021-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_announcements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
