# Generated by Django 3.1.4 on 2021-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_name', models.CharField(default='', max_length=70, verbose_name='Branch')),
                ('code', models.CharField(default='', max_length=15, primary_key=True, serialize=False, verbose_name='Branch Code')),
            ],
        ),
    ]
