# Generated by Django 3.1.4 on 2021-01-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210101_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='enrollment',
        ),
    ]
